"""Recreate Trip table to match BookingPage fields

Revision ID: 06eafd178951
Revises: 2cb1972269c6
Create Date: 2025-10-08 21:09:10.396056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06eafd178951'
down_revision = '2cb1972269c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=True),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lng', sa.Float(), nullable=True),
    sa.Column('dest_lat', sa.Float(), nullable=True),
    sa.Column('dest_lng', sa.Float(), nullable=True),
    sa.Column('origin_address', sa.String(length=255), nullable=True),
    sa.Column('dest_address', sa.String(length=255), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('fare', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    # ### end Alembic commands ###
