"""added trip_date and trip_time

Revision ID: 07e8684b47e3
Revises: 676f4a62d58b
Create Date: 2025-10-09 11:47:43.219238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e8684b47e3'
down_revision = '676f4a62d58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_date', sa.String(length=50), nullable=False, server_default='2025-01-01'))
        batch_op.add_column(sa.Column('trip_time', sa.String(length=50), nullable=False, server_default='00:00'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('trip_time')
        batch_op.drop_column('trip_date')

    # ### end Alembic commands ###
