"""Recreate trip table structure

Revision ID: 676f4a62d58b
Revises: 06eafd178951
Create Date: 2025-10-08 21:19:54.799001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676f4a62d58b'
down_revision = '06eafd178951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(length=100), nullable=False),
    sa.Column('origin_address', sa.String(length=255), nullable=False),
    sa.Column('dest_address', sa.String(length=255), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('fare', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    # ### end Alembic commands ###
